version: "3.9"

services:

  server:
    build: ./server
    restart: always
    ports:
      - "4001:4001"
    depends_on:
      - db
    environment:
      PORT: 4001
      ORIGIN: "http://catan-online.ru"
      DATABASE_USER: my_user
      DATABASE_PASSWORD: "34"
      DATABASE_NAME: my_database
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  client:
    build:
      context: ./client
      args:
        - VITE_SERVER_URL=http://catan-online.ru:4001
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - server

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: "34"
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: